name: f1-forecaster
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
    - fastf1>=3.1.0
    - pytorch-lightning>=2.0.0
    - transformers>=4.30.0
    - streamlit>=1.25.0
    - shap>=0.42.0
    - wandb>=0.15.0
    - omegaconf>=2.3.0
    - hydra-core>=1.3.0
    - plotly>=5.15.0
    - tqdm>=4.65.0
    - submitit>=1.4.5
